OnlineTicariOtomasyon/Models/Sınıflar/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace OnlineTicariOtomasyon.Models.Sınıflar
{
    public class Departman
    {
        [Key]
        public int DepartmanId { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string DepartmanAd { get; set; }
        public bool Durum { get; set; }
        public ICollection<Personel> Personels { get; set; }

    }
}

OnlineTicariOtomasyon/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineTicariOtomasyon.Models.Sınıflar;
using PagedList;

namespace OnlineTicariOtomasyon.Controllers
{
    [Authorize]
    public class DepartmanController : Controller
    {
        // GET: Departman
        private Context context = new Context();
    
        public ActionResult Index(int sayfa = 1)
        {
            var degerler = context.Departmans.ToList().ToPagedList(sayfa, 4);
            return View(degerler);
        }

        [HttpGet]
    
        public ActionResult DepartmanEkle()
        {

            return View();
        }

        [HttpPost]
     
        public ActionResult DepartmanEkle(Departman departman)
        {
            context.Departmans.Add(departman);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmanSil(int id)
        {
            var departman = context.Departmans.Find(id);
            departman.Durum = false;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmanGetir(int id)
        {
            var departman = context.Departmans.Find(id);
            return View("DepartmanGetir", departman);
        }

        public ActionResult DepartmanGuncelle(Departman departman)
        {
            var dept = context.Departmans.Find(departman.DepartmanId);
            dept.DepartmanAd = departman.DepartmanAd;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmanDetay(int id)
        {
            var degerler = context.Personels.Where(x => x.DepartmanId == id).ToList();
            var dpt = context.Departmans.Where(x => x.DepartmanId == id).Select(y=>y.DepartmanAd).FirstOrDefault();
            ViewBag.d = dpt;
            return View(degerler);
        }


        public ActionResult DepartmanPersonelSatis(int id)
        {
            var degerler = context.SatisHarekets.Where(x => x.PersonelId == id).ToList();
            var personel = context.Personels.Where(x => x.PersonelId == id).Select(y => y.PersonelAd).FirstOrDefault();
            ViewBag.p = personel;
            return View(degerler);
        }
    }
}

OnlineTicariOtomasyon/Views/Departman/DepartmanDetay.cshtml
@model List<OnlineTicariOtomasyon.Models.Sınıflar.Personel>
@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br/>
<h2>Departman Detay Sayfası</h2>
<br/>

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">@ViewBag.d</li>
</ol>
<br/>
<table class="table table-hover">
    <tr>
        
        <th>Ad</th>
        <th>Soyad</th>
 
        <th>Satışlar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
        
            <td>@item.PersonelAd</td>
            <td>@item.PersonelSoyad</td>
       
            <td><a href="/Departman/DepartmanPersonelSatis/@item.PersonelId" class="btn btn-info" style="background-color: green">Satışlar</a></td>
        </tr>
    }
  
</table>

OnlineTicariOtomasyon/Views/Departman/DepartmanEkle.cshtml
@model OnlineTicariOtomasyon.Models.Sınıflar.Departman
@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Departman Ekle Sayfası</h2>
<br />

<form class="form-group" method="post">
    @Html.LabelFor(x => x.DepartmanAd)
    @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

OnlineTicariOtomasyon/Views/Departman/DepartmanGetir.cshtml
@model OnlineTicariOtomasyon.Models.Sınıflar.Departman
@{
    ViewBag.Title = "DepartmanGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Departman Güncelleme</h2>
<br />
@* post işlemi yaptıktan sonra hangi sayfa çalışacak *@
@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.DepartmanAd)
        @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
        @Html.HiddenFor(x => x.DepartmanId)
    </div>
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

OnlineTicariOtomasyon/Views/Departman/DepartmanPersonelSatis.cshtml
@model List<OnlineTicariOtomasyon.Models.Sınıflar.SatisHareket>  
@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Departman Personel Satis</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Personel Adı: @ViewBag.p</li>
</ol>
<table class="table table-bordered">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.SatisId</td>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Cariler.CariAd</td>
            <td>@x.Fiyat</td>
            <td>@x.Adet</td>
            <td>@x.ToplamTutar</td>
            <td>@x.Tarih</td>
            <td><a class="btn btn-default" style="background-color: dodgerblue">Yazdır</a></td>
        </tr>

    }


</table>

OnlineTicariOtomasyon/Views/Departman/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<OnlineTicariOtomasyon.Models.Sınıflar.Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<table class="table table-bordered" style="margin-top: 20px">
    <tr>
        <th>Id</th>
        <th>Departman Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detay</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.DepartmanId</td>
            <td>@item.DepartmanAd</td>
            <td><a class="btn btn-danger" href="/Departman/DepartmanSil/@item.DepartmanId">Sil</a></td>
            <td><a class="btn btn-success" href="/Departman/DepartmanGetir/@item.DepartmanId">Güncelle</a></td>
            <td><a class="btn btn-info" href="/Departman/DepartmanDetay/@item.DepartmanId">Detaylar</a></td>
        </tr>
    }

</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))
<a href="/Departman/DepartmanEkle" class="btn btn-primary">Departman Ekle</a>