OnlineTicariOtomasyon/Models/Sınıflar/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace OnlineTicariOtomasyon.Models.Sınıflar
{
    public class Personel
    {
        [Key]
        public int PersonelId { get; set; }

        [Display(Name = "Personel Adı")]
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelAd { get; set; }

        [Display(Name = "Personel Soyadı")]
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelSoyad { get; set; }

        [Display(Name = "Personel Görseli")]
        [Column(TypeName = "Varchar")]
        [StringLength(250)]
        public string PersonelGorsel { get; set; }
        public ICollection<SatisHareket> SatisHarekets { get; set; }

        public int DepartmanId { get; set; }
        public virtual Departman Departman { get; set; }

        public ICollection<Yapilacak> Yapilacaks { get; set; }
    }
}

OnlineTicariOtomasyon/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineTicariOtomasyon.Models.Sınıflar;

namespace OnlineTicariOtomasyon.Controllers
{
    public class PersonelController : Controller
    {
        // GET: Personel
        private Context context = new Context();
        private string connection =
            "data source=(localdb)\\MSSQLLocalDB;initial catalog=KfauAutomationProject;integrated security=True";
        public ActionResult Index()
        {
            DataTable dtbDataTable = new DataTable();
            using (SqlConnection sqlConnection = new SqlConnection(connection))
            {
                sqlConnection.Open();
                SqlDataAdapter sqlData =
                    new SqlDataAdapter("select PersonelAd,PersonelSoyad,PersonelGorsel,DepartmanAd,P.PersonelId" +
                                       "\r\nfrom Personels as P" +
                                       "\r\ninner join Departmen as D" +
                                       "\r\non D.DepartmanId=P.DepartmanId", sqlConnection);
                sqlData.Fill(dtbDataTable);
            }
            // var degerler = context.SatisHarekets.ToList();
            return View(dtbDataTable);
        }

        [HttpGet]
        public ActionResult PersonelEkle()
        { 
            List<SelectListItem> deger1 = (from x in context.Departmans.ToList()
                select new SelectListItem
                {
                    Text = x.DepartmanAd,
                    Value = x.DepartmanId.ToString()
                }).ToList();

            ViewBag.dgr1 = deger1;
            return View();
        }

        [HttpPost]
        public ActionResult PersonelEkle(Personel personel)
        {
            if (Request.Files.Count > 0)
            {
                string dosyaAd = Path.GetFileName(Request.Files[0].FileName);

                string yol = "~/Image/" + dosyaAd;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                personel.PersonelGorsel = "/Image/" + dosyaAd;
            }
            DataTable dtbDataTable = new DataTable();
            using (SqlConnection sqlConnection = new SqlConnection(connection))
            {
                sqlConnection.Open();
                SqlDataAdapter sqlData =
                    new SqlDataAdapter($"INSERT INTO Personels " +
                                       $"(PersonelAd,PersonelSoyad,PersonelGorsel,DepartmanId)" +
                                       $"\r\nVALUES ('{personel.PersonelAd}','{personel.PersonelSoyad}'," +
                                       $"'{personel.PersonelGorsel}','{personel.DepartmanId}');", sqlConnection);
                sqlData.Fill(dtbDataTable);
            }
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PersonelGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in context.Departmans.ToList()
                select new SelectListItem
                {
                    Text = x.DepartmanAd,
                    Value = x.DepartmanId.ToString()
                }).ToList();

            ViewBag.dgr1 = deger1;
            var personel = context.Personels.Find(id);
            return View("PersonelGetir", personel);
        }

        public ActionResult PersonelGuncelle(Personel personel)
        {
            if (Request.Files.Count > 0)
            {
                string dosyaAd = Path.GetFileName(Request.Files[0].FileName);

                string yol = "~/Image/" + dosyaAd;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                personel.PersonelGorsel = "/Image/" + dosyaAd;
            }
            DataTable dtbDataTable = new DataTable();
            using (SqlConnection sqlConnection = new SqlConnection(connection))
            {
                sqlConnection.Open();
                SqlDataAdapter sqlData =
                    new SqlDataAdapter($"UPDATE Personels" +
                                       $"\r\nSET PersonelAd = '{personel.PersonelAd}', " +
                                       $"\r\nPersonelSoyad= '{personel.PersonelSoyad}'," +
                                       $"\r\nPersonelGorsel = '{personel.PersonelGorsel}'," +
                                       $"\r\nDepartmanId = {personel.DepartmanId}" +
                                       $"\r\nWHERE PersonelId = {personel.PersonelId};", sqlConnection);

                sqlData.Fill(dtbDataTable);
            }
            //var prs = context.Personels.Find(personel.PersonelId);
            //prs.PersonelAd = personel.PersonelAd;
            //prs.PersonelSoyad = personel.PersonelSoyad;
            //prs.PersonelGorsel = personel.PersonelGorsel;
            //prs.DepartmanId = personel.DepartmanId;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PersonelListe()
        {
            var sorgu = context.Personels.ToList();
            return View(sorgu);

        }
    }

}

OnlineTicariOtomasyon/Views/Personel/Index.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top: 20px">
    <tr>
        <th>Personel Adı</th>
        <th>Personel Soyad</th>
        <th>Personel Görsel</th>
        <th>Departman</th>
        <th>Güncelle</th>
        <th>Satışlar</th>
    </tr>

    @for(int i=0;i<Model.Rows.Count;i++)
    {
        <tr>
            <td>@Model.Rows[i][0]</td>
            <td>@Model.Rows[i][1]</td>
            <td>
                <img src="@Model.Rows[i][2]" style="width: 150px;height: 100px"/>
            </td>
            @*<td>@Model.Rows[i][2]</td>*@
            <td>@Model.Rows[i][3]</td>
            <td><a class="btn btn-success" href="/Personel/PersonelGetir/@Model.Rows[i][4]">Güncelle</a></td>
            <td><a class="btn btn-info" href="/Departman/DepartmanPersonelSatis/@Model.Rows[i][4]">Satışlar</a></td>
        </tr>
    }

</table>
<a href="/Personel/PersonelEkle" class="btn btn-primary">Personel Ekle</a>

OnlineTicariOtomasyon/Views/Personel/PersonelEkle.cshtml
@model OnlineTicariOtomasyon.Models.Sınıflar.Personel
@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Personel Sayfası</h2>
<br />
@using (Html.BeginForm("PersonelEkle", "Personel", FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    <form class="form-group" method="post">
        @Html.LabelFor(x => x.PersonelAd)
        @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.PersonelSoyad)
        @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.PersonelGorsel)
        <input type="file" name="PersonelGorsel"/>
        <br />
        @Html.LabelFor(x => x.Departman)
        @Html.DropDownListFor(x => x.DepartmanId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        <br/>
        <button class="btn btn-primary">Kaydet</button>
    </form>


}

OnlineTicariOtomasyon/Views/Personel/PersonelGetir.cshtml
@model OnlineTicariOtomasyon.Models.Sınıflar.Personel
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<br />
<h2>Personel Güncelleme Ekranı</h2>
<br />

@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.PersonelId)
        @Html.LabelFor(x => x.PersonelAd)
        @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.PersonelSoyad)
        @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.PersonelGorsel)
        <input type="file" name="PersonelGorsel"/>
        <br />
        @Html.LabelFor(x => x.Departman)
        @Html.DropDownListFor(x => x.DepartmanId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        <br />
        <button class="btn btn-default" style="background-color: yellowgreen">Güncelle</button>
    </div>
}

OnlineTicariOtomasyon/Views/Personel/PersonelListe.cshtml
@model List<OnlineTicariOtomasyon.Models.Sınıflar.Personel>
@{
    ViewBag.Title = "PersonelListe";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Contacts</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">

            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>Personeller</h1>
                        </div>
                      
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">

                <!-- Default box -->
                <div class="card card-solid">
                    <div class="card-body pb-0">
                        <div class="row d-flex align-items-stretch">
                            @foreach (var x in Model)
                            {
                                <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                                <div class="card bg-light">
                                    <div class="card-header text-muted border-bottom-0">
                                        @x.Departman.DepartmanAd
                                    </div>
                                    <div class="card-body pt-0">

                                        <div class="row">
                                            <div class="col-7">
                                                <h2 class="lead"><b>@x.PersonelAd @x.PersonelSoyad</b></h2>
                                                <p class="text-muted text-sm"><b>About: </b> Web Designer / UX / Graphic Artist / Coffee Lover </p>
                                                <ul class="ml-4 mb-0 fa-ul text-muted">
                                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                                                </ul>
                                            </div>
                                            <div class="col-5 text-center">
                                                <img src="@x.PersonelGorsel" alt="" class="img-circle img-fluid">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-footer">
                                        <div class="text-right">
                                            <a href="/Personel/PersonelGetir/@x.PersonelId" class="btn btn-sm bg-teal">
                                                <i class="fas fa-comments"></i>
                                            </a>
                                            <a href="/Departman/DepartmanPersonelSatis/@x.PersonelId" class="btn btn-sm btn-primary">
                                                <i class="fas fa-user"></i> Satış Geçmişi
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            }
                        </div>
                    <!-- /.card-body -->
                    </div>
                    <!-- /.card-footer -->
                </div>
                <!-- /.card -->
            </section>

    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
</body>
</html>