OnlineTicariOtomasyon/Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineTicariOtomasyon.Models.Sınıflar;

namespace OnlineTicariOtomasyon.Controllers
{
    public class SatisController : Controller
    {
        // GET: Satis
        private Context context = new Context();

        private string connection =
            "data source=(localdb)\\MSSQLLocalDB;initial catalog=KfauAutomationProject;integrated security=True";

 
        public ActionResult Index()
        {
            DataTable dtbDataTable = new DataTable();
            using (SqlConnection sqlConnection = new SqlConnection(connection))
            {
                sqlConnection.Open();
                SqlDataAdapter sqlData = 
                    new SqlDataAdapter("SELECT SatisId,UrunAd,CariAd,PersonelAd,Adet,Fiyat,ToplamTutar,Tarih,SH.PersonelId" +
                                       "\r\nFROM SatisHarekets as SH" +
                                       "\r\nINNER JOIN Uruns AS U" +
                                       "\r\nON U.UrunId = SH.UrunId  " +
                                       "\r\nINNER JOIN Personels AS p" +
                                       "\r\nON P.PersonelId = SH.PersonelId" +
                                       "\r\nINNER JOIN Carilers AS C" +
                                       "\r\nON C.CariId = SH.CariId \r\n", sqlConnection);
                sqlData.Fill(dtbDataTable);
            }
            // var degerler = context.SatisHarekets.ToList();
            return View(dtbDataTable);
        } 

        [HttpGet]
        public ActionResult YeniSatis()
        {
            List<SelectListItem> deger1 = (from x in context.Uruns.ToList()
                select new SelectListItem()
                {
                    Text = x.UrunAd,
                    Value = x.UrunId.ToString()
                }).ToList();

            List<SelectListItem> deger2 = (from x in context.Carilers.ToList()
                select new SelectListItem()
                {
                    Text = x.CariAd,
                    Value = x.CariId.ToString()
                }).ToList();

            List<SelectListItem> deger3 = (from x in context.Personels.ToList()
                select new SelectListItem()
                {
                    Text = x.PersonelAd,
                    Value = x.PersonelId.ToString()
                }).ToList();

            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;

            return View();
        }

        [HttpPost]
        public ActionResult YeniSatis(SatisHareket satisHareket)
        {
            //satisHareket.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());

            //context.SatisHarekets.Add(satisHareket);
            DataTable dtbDataTable = new DataTable();
            using (SqlConnection sqlConnection = new SqlConnection(connection))
            {
                sqlConnection.Open();
                SqlDataAdapter sqlData =
                    new SqlDataAdapter($"insert into SatisHarekets " +
                                       $"(UrunId,CariId,PersonelId,Adet,Fiyat,ToplamTutar,Tarih)" +
                                       $"\r\nvalues ('{satisHareket.UrunId}','{satisHareket.CariId}'," +
                                       $"'{satisHareket.PersonelId}','{satisHareket.Adet}'," +
                                       $"'{satisHareket.Fiyat}','{satisHareket.ToplamTutar}',GETDATE()); ", sqlConnection);
                sqlData.Fill(dtbDataTable);
            }
       
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in context.Uruns.ToList()
                select new SelectListItem()
                {
                    Text = x.UrunAd,
                    Value = x.UrunId.ToString()
                }).ToList();

            List<SelectListItem> deger2 = (from x in context.Carilers.ToList()
                select new SelectListItem()
                {
                    Text = x.CariAd,
                    Value = x.CariId.ToString()
                }).ToList();

            List<SelectListItem> deger3 = (from x in context.Personels.ToList()
                select new SelectListItem()
                {
                    Text = x.PersonelAd,
                    Value = x.PersonelId.ToString()
                }).ToList();

            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            var deger = context.SatisHarekets.Find(id);
            return View("SatisGetir", deger);
        }

        public ActionResult SatisGuncelle(SatisHareket satisHareket)
        {
            var deger = context.SatisHarekets.Find(satisHareket.SatisId);
            deger.CariId = satisHareket.CariId;
            deger.Adet = satisHareket.Adet;
            deger.Fiyat = satisHareket.Fiyat;
            deger.PersonelId = satisHareket.PersonelId;
            deger.Tarih = satisHareket.Tarih;
            deger.ToplamTutar = satisHareket.ToplamTutar;
            deger.UrunId = satisHareket.UrunId;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisDetay(int id)
        {
            var degerler = context.SatisHarekets.Where(x => x.SatisId == id).ToList();
            return View(degerler);
        }

    }
}

OnlineTicariOtomasyon/Views/Satis/Index.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br/>
<table id="tbl1" class="table table-bordered" style="margin-top: 20px">
    <thead>


        <tr>
            <th>Id</th>
            <th>Ürün</th>
            <th>Cari</th>
            <th>Personel</th>
            <th>Adet</th>
            <th>Fiyat</th>
            <th>Toplam</th>
            <th>Tarih</th>
            <th>Güncelle</th>
            <th>Detaylar</th>
        </tr>
    </thead>
    @for (int i = 0; i < Model.Rows.Count; i++)
    {
        <tr>
            <td>@Model.Rows[i][0]</td>
            <td>@Model.Rows[i][1]</td>
            <td>@Model.Rows[i][2]</td>
            <td>@Model.Rows[i][3]</td>
            <td>@Model.Rows[i][4]</td>
            <td>@Model.Rows[i][5]</td>
            <td>@Model.Rows[i][6]</td>
            <td>@Model.Rows[i][7]</td>
            <td><a class="btn btn-success" href="/Satis/SatisGetir/@Model.Rows[i][0]">Güncelle</a></td>
            <td><a class="btn btn-info" href="/Satis/SatisDetay/@Model.Rows[i][0]">Satışlar</a></td>

        </tr>
    }

</table>
<a href="/Satis/YeniSatis" class="btn btn-primary">Yeni Satış Yap</a>



<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>




<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<script>
    $('#tbl1').dataTable({});
</script>

OnlineTicariOtomasyon/Views/Satis/SatisDetay.cshtml
@model List<OnlineTicariOtomasyon.Models.Sınıflar.SatisHareket>
@{
    ViewBag.Title = "SatisDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Satis Detayı</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
      
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.SatisId</td>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Cariler.CariAd</td>
            <td>@x.Personel.PersonelAd</td>
            <td>@x.Fiyat</td>
            <td>@x.Adet</td>
            <td>@x.ToplamTutar</td>
            <td>@x.Tarih</td>
            
        </tr>

    }

</table>
<button class="btn btn-default" style="background-color: dodgerblue">Yazdır</button>

OnlineTicariOtomasyon/Views/Satis/SatisGetir.cshtml
@model OnlineTicariOtomasyon.Models.Sınıflar.SatisHareket
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Satış Güncelleme Sayfası</h2>
<br />


@using (Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post))
{
    @Html.HiddenFor(x => x.SatisId)
    <br/>
    @Html.LabelFor(x => x.Urun)
    @Html.DropDownListFor(x => x.UrunId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.Label("Cari")
    @Html.DropDownListFor(x => x.CariId, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Personel)
    @Html.DropDownListFor(x => x.PersonelId, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Adet)
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Fiyat)
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ToplamTutar)
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tarih)
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <br />

    <button class="btn btn-warning">Güncelle</button>

}

OnlineTicariOtomasyon/Views/Satis/YeniSatis.cshtml
@model OnlineTicariOtomasyon.Models.Sınıflar.SatisHareket
@{
    ViewBag.Title = "YeniSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Satış Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.Urun)
    @Html.DropDownListFor(x => x.UrunId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.Label("Cari")
    @Html.DropDownListFor(x => x.CariId, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })

    <br />
    @Html.LabelFor(x => x.Personel)
    @Html.DropDownListFor(x => x.PersonelId, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Adet)
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Fiyat)
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ToplamTutar)
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />

    <button class="btn btn-primary">Satış Yap</button>
</form>